# Generated by Django 6.0.6 on 2026-08-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_lowstockalert'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lowstockalert',
            name='unique_active_low_stock_alert',
        ),
        migrations.AlterField(
            model_name='lowstockalert',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alert', to='products.product'),
        ),
    ]
